# Generated by Django 5.1.3 on 2026-01-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
    ]
