from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model  
from boards.models import Board
from lists.models import List
from cards.models import Card

User=get_user_model()

class Command(BaseCommand):
    help='Seed ths databases with a sample Kanban Board'
    def handle(self, *args, **kwargs):
        user=User.objects.first()
        if not user:
            self.stdout.write(self.style.ERROR("No users found! Create a superuser first."))
            return
        self.stdout.write(f"Seeding data for user: {user.username}...")

        board,created=Board.objects.get_or_create(
            name="Sample Board",
            defaults={
                "owner":user,
            }
        )
        if created:
            self.stdout.write(self.style.SUCCESS(f"Created board: {board.name}"))
        else:
            self.stdout.write(self.style.WARNING(f"Board {board.name} already exists."))

        list_names=["To Do", "In Progress", "Code Review", "Done"]
        lists={}

        for index,title in enumerate(list_names):
            lst,_=List.objects.get_or_create(
                title=title,
                board=board,
                defaults={'position':index}
            )
            lists[title]=lst
            self.stdout.write(f" - Verifies List: {title}")

        cards_data=[
            ("Setup Django Backend", "Done", 0),
            ("Configure Supabase DB", "Done", 1),
            ("Implement JWT Auth", "In Progress", 0),
            ("Build React Frontend", "In Progress", 1),
            ("Integrate Drag and Drop", "To Do", 0),
            ("Deploy to AWS EC2", "To Do", 1),
            ("Fix Docker Containers", "To Do", 2),
        ]

        for title,list_name,position in cards_data:
            target_list=lists[list_name]
            Card.objects.get_or_create(
                title=title,
                parent_list=target_list,
                defaults={
                    "position":position,
                    'description':'Generated by seed script'
                }
            )
        self.stdout.write(self.style.SUCCESS("Successfully seeded the database."))
        